package org.darr.mirr.model.profile;

import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.ToString;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.StringReader;
import java.util.List;
import java.util.Map;
import java.util.function.Function;
import java.util.function.Predicate;
import java.util.stream.IntStream;
import java.util.stream.Stream;

import static java.util.stream.Collectors.joining;
import static java.util.stream.Collectors.toMap;
import static org.darr.mirr.model.profile.CharStatEnum.*;
import static org.darr.mirr.util.function.FunctionUtil.predicate;

@Getter
@ToString
@RequiredArgsConstructor
public class CharacterStats {
    private static final String FILE_NAME_SUFFIX = "_stats.char";
    private static final List<String> STATS_NAMES_GROUP1 = List.of(UNIT_CLASS.strValue, UNIT_SIDE.strValue, SHIP.strValue,
            ATTACK_TYPE.strValue, LEVEL.strValue, SIDE.strValue, EXP_BASE.strValue);
    private static final List<String> STATS_NAMES_GROUP2 = List.of(STR.strValue, SPD.strValue, DEX.strValue, AGI.strValue, VIT.strValue);
    private static final List<String> STATS_NAMES_GROUP3 = List.of(AP.strValue, UP.strValue, MOV.strValue, MOVWM.strValue);
    private static final List<String> STATS_NAMES_GROUP4 = List.of(ATCK_RANGE.strValue, ZONE_RADIUS.strValue, ATCK_ZONE.strValue,
            CONTROL.strValue, COVER.strValue);
    private static final List<String> STATS_NAMES_GROUP5 = List.of(DEF.strValue, RES.strValue, RES_SLASH.strValue,
            RES_PIERCE.strValue, RES_BLUNT.strValue, RES_FIRE.strValue, RES_WATER.strValue, RES_AIR.strValue, RES_EARTH.strValue,
            RES_DEATH.strValue, RES_MIND.strValue);
    private static final List<String> STATS_NAMES_GROUP6 = List.of(HEALER.strValue, LANDGUARDIAN.strValue, RACELEADER.strValue,
            LEADERSHIP.strValue, LEADERSHIP_COST.strValue, COST.strValue, SKILL_GRID.strValue, VIEWRADIUS.strValue);
    private static final List<String> STATS_NAMES_GROUP7 = List.of(DMG_STR_MOD.strValue, DMG_AGI_MOD.strValue,
            CRIT_DEX_MOD.strValue, CRIT_VIT_MOD.strValue, FLEE_AGI_MOD.strValue, FLEE_SPD_MOD.strValue, HP_VIT_MOD.strValue,
            HP_STR_MOD.strValue, INI_SPD_MOD.strValue, INI_DEX_MOD.strValue, MOV_MOD.strValue, MOVWM_MOD.strValue,
            COVER_MOD.strValue, VIEWRADIUS_MOD.strValue, REGEN_MOD.strValue, DISCOUNT_MOD.strValue, BONUSEXP_MOD.strValue,
            LEVEL_CAP.strValue, LEVELS_TO_UP.strValue);

    private final String name;
    private final Map<String, String> lineMap;

    public int count() {
        return lineMap.size();
    }

    public String getStatValue(String key) {
        return lineMap.get(key);
    }

    public Line getLine(String key) {
        return new Line(key, getStatValue(key));
    }

    public Map<String, String> toFileContent() {
        var contentString = Stream
                .of(
                        Stream.of(
                                new Line("// Characters stats profile", ""),
                                new Line("// auto-generated by dis3-modding-automation", ""),
                                Line.EMPTY
                        ),
                        toStatsLine(STATS_NAMES_GROUP1),
                        Stream.of(Line.EMPTY, new Line("// stats", "")),
                        toStatsLine(STATS_NAMES_GROUP2),
                        Stream.of(Line.EMPTY),
                        toStatsLine(STATS_NAMES_GROUP3),
                        Stream.of(Line.EMPTY),
                        toStatsLine(STATS_NAMES_GROUP4),
                        Stream.of(Line.EMPTY, new Line("// resists", "")),
                        toStatsLine(STATS_NAMES_GROUP5),
                        Stream.of(Line.EMPTY),
                        toStatsLine(STATS_NAMES_GROUP6),
                        Stream.of(Line.EMPTY, new Line("// Modifi", "")),
                        toStatsLine(STATS_NAMES_GROUP7)
                )
                .reduce(Stream.empty(), Stream::concat)
                .filter(line ->
                        line.statValue != null)
                .map(Line::toString)
                .collect(joining(System.lineSeparator()));
        var fileName = name + FILE_NAME_SUFFIX;
        return Map.of(fileName.toLowerCase(), contentString);
    }

    private Stream<Line> toStatsLine(List<String> statNames) {
        return statNames
                .stream()
                .map(this::getLine);
    }

    public static CharacterStats of(String name, String content) throws IOException {
        try (var reader = new BufferedReader(new StringReader(content))) {
            var lineMap = reader
                    .lines()
                    .map(String::trim)
                    .filter(redundantLines())
                    .map(line ->
                            line.replaceAll("\"", ""))
                    .map(Line::of)
                    .collect(toMap(line -> line.statName, line -> line.statValue));
            return new CharacterStats(toCharacterName(name), lineMap);
        }
    }

    private static String toCharacterName(String name) {
        return name.endsWith(FILE_NAME_SUFFIX) ? name.split(FILE_NAME_SUFFIX)[0] : name;
    }

    private static Predicate<String> redundantLines() {
        return predicate(String::isEmpty)
                .or(String::isBlank)
                .or(string -> string.startsWith("//"))
                .negate();
    }

    @Getter
    @RequiredArgsConstructor
    public static class Line {
        private static final Line EMPTY = new Line("", "");
        private static final int LINE_LENGTH_MAX = 40;
        private final String statName;
        private final String statValue;
        private String toString;

        private static Line of(String line) {
            if (line.endsWith(";")) {
                line = cutOffLastChar(line);
            }
            if (line.contains(" ") || line.contains("\t")) {
                var parts = line.split("[ |\t]");
                var partList = removeSpacesBetweenKeyAndValue(parts);
                var key = partList.get(0);
                var value = partList.get(1);
                return new Line(key, value);
            } else {
                // for boolean values like Healer, Landguardian, etc.
                return new Line(line, "1");
            }
        }

        private static List<String> removeSpacesBetweenKeyAndValue(String[] parts) {
            return Stream
                    .of(parts)
                    .map(String::trim)
                    .filter(redundantLines())
                    .toList();
        }

        private static String cutOffLastChar(String string) {
            return string.substring(0, string.length() - 1);
        }

        private String getSpaceString() {
            int statValueLength = statValue == null ? 4 : statValue.length();
            int contentLength = statName.length() + statValueLength;

            // TODO: Looks quite weird. Is it possible to make better?
            int spaceCount = LINE_LENGTH_MAX - contentLength;
            spaceCount = CharStatEnum
                    .findByStrValueSafety(statName)
                    .map(resolveSpaceCount(spaceCount))
                    .orElse(spaceCount);

            return IntStream
                    .rangeClosed(1, spaceCount)
                    .mapToObj(intCount -> " ")
                    .collect(joining(""));
        }

        @Override
        public String toString() {
            if (toString == null) {
                this.toString = evaluateToString();
            }
            return toString;
        }

        private String evaluateToString() {
            var statValueResolved = CharStatEnum
                    .findByStrValueSafety(statName)
                    .map(resolveStatValue())
                    .orElse(statValue);
            var spaceString = getSpaceString();
            var endChar = statName.startsWith("//") || this == EMPTY ? "" : ";";

            return statName + spaceString + statValueResolved + endChar;
        }

        private Function<CharStatEnum, String> resolveStatValue() {
            return charStatEnum -> {
                if (charStatEnum.type == ValueType.BOOLEAN) {
                    return "";
                }
                if (charStatEnum.isQuoted) {
                    return "\"" + statValue + "\"";
                }
                return statValue;
            };
        }

        private Function<CharStatEnum, Integer> resolveSpaceCount(int spaceCount) {
            return charStatEnum -> {
                if (charStatEnum.type == ValueType.BOOLEAN) {
                    return 0;
                }
                if (charStatEnum.isQuoted) {
                    return spaceCount - 2;
                }
                return spaceCount;
            };
        }
    }
}
